server:
  port: 0

spring:
  application:
    name: storage-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: admin123
      secret-key: 321admin
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: malurus-storages

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
